version: '3.1'

services:
  bot-tb:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'tb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  bot:
    depends_on:
      - bot-tb
    build:
      context: .
    environment:
      BOT_NAME: $BOT_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_DB_USERNAME: $BOT_DB_USERNAME
      BOT_DB_PASSWORD: $BOT_DB_PASSWORD
    restart: always